export const motivatingLines = [
  "Hyperfocus activated! You're on fire!",
  "The timer didn't stand a chance against your brain today.",
  "Dopamine hit! You just crushed that task.",
  "Fast as lightning! What's next on the hit list?",
  "Brain: 1, Procrastination: 0. Keep the streak alive!",
  "You're beating the clock like a pro. Ride that momentum!",
  "Momentum is your superpower. Keep the wave rolling!",
  "Look at you go! You're a productivity machine!",
  "That was fast! Your focus is legendary.",
  "You're in the zone. Don't stop now!",
  "Boom! Task destroyed. Keep that energy high!",
  "You're outrunning your own schedule. Impressive!",
  "Your brain is clicking today. Let's keep it up!",
  "Level up! You're crushing these goals.",
  "Speedy and efficient. You're killing it!",
  "The clock is sweating trying to keep up with you.",
  "You just proved you're the boss of your time.",
  "That focus was intense! Ready for the next challenge?",
  "You're on a roll. Let's see how far you can go!",
  "Productivity level: GOD MODE.",
  "You're making this look easy. Keep going!",
  "Who knew you could be this fast? (I did!)",
  "You're slicing through tasks like a hot knife through butter.",
  "Stay in that flow! You're doing amazing.",
  "The ADHD tax? Not today! You're winning.",
  "Your future self is high-fiving you right now.",
  "That's how you do it! Keep that focus locked in.",
  "You're a task-finishing wizard!",
  "Lightning fast! Your brain is in top gear.",
  "Checkmate, Procrastination. Next move?",
  "You're essentially a superhero at this point.",
  "That task never had a chance. Keep the pressure on!",
  "You're outperforming your yesterday-self!",
  "Focus game: STRONG. Let's keep the momentum.",
  "You're a productivity ninja. Quiet, fast, and effective.",
  "Boom! Another one bites the dust.",
  "Your focus is sharper than a diamond today.",
  "You're making massive progress. Don't lose the scent!",
  "You're a whirlwind of productivity!",
  "The timer is crying in the corner. You're too fast!",
  "You're in 'The Flow' now. Keep riding it!",
  "That was a masterclass in getting things done.",
  "You're breaking records today! Keep it up.",
  "Your brain is firing on all cylinders. Majestic!",
  "Pure efficiency! You're on a whole different level.",
  "You're crushing your to-do list like a boss.",
  "Incredible speed! What's your secret? (It's your awesome brain.)",
  "You're a force of nature today!",
  "Task complete! Your momentum is unstoppable.",
  "You're dancing through your day. Keep the rhythm!",
  "Total domination! Keep that focus sharp.",
  "You're outrunning the sun today. Stay bright!",
  "That focus was surgical. Precision work!",
  "You're a productivity rockstar! Encore!",
  "Victory! You're beating the clock and winning at life.",
  "You're a task-slaying machine!",
  "Your focus is electric today! Keep the sparks flying.",
  "You're light-years ahead. Keep the warp drive engaged!",
  "That was spectacular! Ready for the next win?",
  "You're a productivity legend in the making.",
  "You're rewriting the rules of focus today.",
  "Incredible! You're moving at the speed of thought.",
  "You're a task-conquering titan!",
  "Your brain is a precision instrument today.",
  "You're leaving the clock in the dust!",
  "That was pure gold. Keep the streak going!",
  "You're a focus phenom! Don't slow down now.",
  "You're absolutely crushing it. Keep that fire burning!",
  "Task: Obliterated. Ego: Boosted. Go again?",
  "You're a productivity champion. Wear the crown!",
  "Your focus is unmatched today. Stay in the zone!",
  "You're a whirlwind of efficiency! Keep spinning.",
  "That was lightning in a bottle. Let's catch some more!",
  "You're a task-finishing powerhouse!",
  "You're officially too fast for this timer. Keep it up!"
];
